M48
; DRILL file KiCad 10.0.3 date 2026-05-27T13:41:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-27T13:41:34+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X88.42Y-66.5
X98.58Y-66.5
T2
X86.0Y-83.0
X88.54Y-83.0
M30
